### ISSUE TITLE
 Close battle scheduled (reason: unable to retrieve map hashcode) on newest engines

### ISSUE THREAD

**Issue by TurBoss** [Yaribz/SPADS#13]
seems to be related to unitsync deprecated functions

**Comment by Yaribz** [comment]
Why do you think it is related to unitsync deprecated functions, do you have any log related to your problem? (spads.log, unitsync.log, stdout...)

**Comment by Yaribz** [comment]
Did you find out what happened?

**Comment by TurBoss** [comment]
no sry I'm a bit busy
