### ISSUE TITLE
Resource bonus

### ISSUE THREAD

**Issue by specing** [Yaribz/SPADS#17]
Would it be possible to add a command to adjust resource bonuses? I haven't found a way to do so yet (without adding code).

Negative bonuses as well if possible.

**Comment by Yaribz** [comment]
The [lobby protocol](http://springrts.com/dl/LobbyProtocol/ProtocolDescription.html#HANDICAP:client) and [start script format documentation](https://raw.githubusercontent.com/spring/spring/develop/doc/StartScriptFormat.txt) aren't very consistent about the way the bonus values are supposed to be sent/managed by lobby clients. I will have to check if it's possible to implement something compatible with all lobby clients... If it's possible, then I will implement your request as a new syntax for the !force command, for example: "!force player bonus 1"

**Comment by Yaribz** [comment]
Only positive bonus amounts can be configured, because the lobby protocol doesn't allow negative values...
