### ISSUE TITLE
Updater is touching the lockfile several times per second

### ISSUE THREAD

**Issue by specing** [Yaribz/SPADS#21]
for ((;;)); do find-latest .; done
2017-04-19+22:33:29.1996291220 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:29.1996291220 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:30.1129624620 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:30.1129624620 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:31.0862958020 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:31.1162958020 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:31.1162958020 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:32.2896291430 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:32.2896291430 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:32.2896291430 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:33.3029624820 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:33.3029624820 ./install/103.0/SpadsUpdater.lock
2017-04-19+22:33:34.3062958220 ./install/103.0/SpadsUpdater.lock
...

iotop is hinting at spads.pl as the top writer at ~78 KB/s

**Comment by Yaribz** [comment]
Do you have several instances of SPADS running sharing same binaries ?

**Comment by specing** [comment]
Yes, 3 of them at the moment. Ok.

**Comment by Yaribz** [comment]
The updater was indeed checking the lock file way too often because of a bad ordering in the update checks. I fixed this in SPADS 0.11.43a ( 5297b1b ), thanks for the report.

However what do you mean by "become a problem" ? Did you notice any performance problem? In this case I don't think this is related to this minor i/o overhead...

**Comment by specing** [comment]
Now I have the same problem with 100.0 autohost (only one SPADS instance with these binaries)

SPADS is not "checking" the lock file, but touching it:

$ stat install/100.0/SpadsUpdater.lock 
  File: 'install/100.0/SpadsUpdater.lock'
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 27h/39d Inode: 135841      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/     s44)   Gid: ( 1000/     s44)
Access: 2017-01-05 00:58:39.649587125 +0100
Modify: 2017-04-22 11:51:47.717708344 +0200
Change: 2017-04-22 11:51:47.717708344 +0200

$ stat install/100.0/SpadsUpdater.lock 
  File: 'install/100.0/SpadsUpdater.lock'
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 27h/39d Inode: 135841      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/     s44)   Gid: ( 1000/     s44)
Access: 2017-01-05 00:58:39.649587125 +0100
Modify: 2017-04-22 11:51:48.717708354 +0200
Change: 2017-04-22 11:51:48.717708354 +0200


Due to how btrfs works, these small writes resulted in about 2MB/s being written to disk.

**Comment by Yaribz** [comment]
By "checking" I meant locking/unlocking the file, to check it is not already locked by another updater instance, which indeed accesses the file and modifies timestamps.

**Comment by Yaribz** [comment]
2MB seems a huge overhead for a few lock/unlock file operations...
Are you sure the operations on the SpadsUpdater.lock file are the culprit ?

**Comment by specing** [comment]
Yes. They are amplified due to how btrfs works (copy of the whole metadata tree up to root of filesystem). The actual writes by SPADS as reported by iotop were roughly ~78 KB/s.

**Comment by Yaribz** [comment]
This should be fixed in SPADS 0.11.43a, comment/reopen if needed.
