### ISSUE TITLE
SPADS death with infinite spam of uninitialised values to console

### ISSUE THREAD

**Issue by specing** [Yaribz/SPADS#22]
Probably triggered by lobby server upgrade. Other two SPADS instances were unaffected and this one starts normally without problems after killing it.

Use of uninitialized value $bot in hash element at ./spads.pl line 3826.
Use of uninitialized value $groupNb in array element at ./spads.pl line 3824.
Use of uninitialized value $groupNb in array element at ./spads.pl line 3825.
Use of uninitialized value $bot in hash element at ./spads.pl line 3825.
Use of uninitialized value in addition (+) at ./spads.pl line 3825.
Use of uninitialized value $bot in hash element at ./spads.pl line 3826.
Use of uninitialized value $groupNb in array element at ./spads.pl line 3826.
Use of uninitialized value $bot in hash element at ./spads.pl line 3826.
Use of uninitialized value $groupNb in array element at ./spads.pl line 3824.
Use of uninitialized value $groupNb in array element at ./spads.pl line 3825.
Use of uninitialized value $bot in hash element at ./spads.pl line 3825.
Use of uninitialized value in addition (+) at ./spads.pl line 3825.
Use of uninitialized value $bot in hash element at ./spads.pl line 3826.
Use of uninitialized value $groupNb in array element at ./spads.pl line 3826.
Use of uninitialized value $bot in hash element at ./spads.pl line 3826.
Use of uninitialized value $groupNb in array element at ./spads.pl line 3824.
Use of uninitialized value $groupNb in array element at ./spads.pl line 3825.
...

**Comment by Yaribz** [comment]
Yes, it is  due to the lobby server sending inconsistent data because of dev testing their code on the main lobby server. [I though I had protected SPADS against all sort of bugs in lobby server](https://springrts.com/phpbb/viewtopic.php?f=88&t=33147), but it seems I have forgotten some...

I guess you don't have the errors preceding these ones still in your buffer ?
Was SPADS still responding to commands when it happened ?

**Comment by specing** [comment]
That bot was not connected to the lobby during spam, and the spam quickly filled my console's scrollback.

**Comment by Yaribz** [comment]
Yeah I see, the inconsistent data caused a loop in SPADS auto-balancing system, which made it timeout from lobby server point of view... So it wouldn't have responded to any command anyway.
Can you check your spads.log file and see what are the last lines before your restart ?

**Comment by specing** [comment]
last 14 hours or so: https://paste.pound-python.org/show/QPE21gbDzCi5YxghOV50/

**Comment by Yaribz** [comment]
Perfect, thanks.
It confirms what I thought...
