### ISSUE TITLE
error "Can't locate SimpleEvent.pm in @INC" at launch on Archlinux

### ISSUE THREAD

**Issue by TurBoss** [Yaribz/SPADS#24]
hello:

Today I upgraded my Arch server
seems that new perl is used and is not able to locate local modules like SimpleEvent and SimpleLog when launching spads

```
This is perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux-thread-multi
```

spads shows

```
Can't locate SimpleEvent.pm in @INC (you may need to install the SimpleEvent module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at ./spads.pl line 38.
BEGIN failed--compilation aborted at ./spads.pl line 38.
```

Thanks

**Comment by TurBoss** [comment]
Thanks to Fabs

I have added PERL5LIB to the systemd unit now works fine

Thanks

**Comment by Yaribz** [comment]
Which version of SPADS are you using? FYI this should be fixed in SPADS 0.11.46a, which should be in testing release soon (only in unstable for now).

**Comment by TurBoss** [comment]
hello

did a upgraded to unstable from testing

**Comment by Yaribz** [comment]
This is included in "testing" release now, so you can switch back to "testing" if you want (and remove the PERL5LIB definition).

**Comment by TurBoss** [comment]
Thanks
