### ISSUE TITLE
Unintelligible SPADS messages

### ISSUE THREAD

**Issue by specing** [Yaribz/SPADS#25]
Could something be done about these messages? I doubt any newbie would know that in some context
"you are not allowed to call command "start" in current context."
means "you are not allowed to call command "start" while being a spectator"

**Comment by Yaribz** [comment]
That's not that simple, the rules for each command are entirely customizable... For example there could be tons of ways for one given command to become runnable by changing only one context parameter (player/playing/spectator, rank, game running state etc.).

If you can explain me exactly what you want through an algorithm which takes the list of rules for a given command as parameter and outputs the message you think it should print when none of the rules allows the command to be executed, then I could try to implement it.
