### ISSUE TITLE
restoreDefaultPresetDelay

### ISSUE THREAD

**Issue by FabriceFABS** [Yaribz/SPADS#28]
Hi ! How ya ?
Fonction `restoreDefaultPresetDelay:30`
`[11:31:23]	<*>	[ACE]Sure * Battle empty for 30 seconds, restoring default settings`

This cannot be executed in `[ACE]Pirine` due to the presence of a bot.
Is it possible to restore defaults settings, even with presence of specs (or bots...) ?
Or eventually the possibility to choose restoring with or without specs...

Thx !

**Comment by Yaribz** [comment]
I fixed SPADS so it ignores lobby accounts tagged as bot when checking if battle is empty for automatic default preset restoration and automatic map/preset rotation when battle is empty.

**Comment by FabriceFABS** [comment]
Merci Super pour le coup double !

**Comment by Yaribz** [comment]
FYI in commit 62846a5 (SPADS 0.11.46g) I also made SPADS ignore lobby accounts tagged as bot when checking if battle is empty for automatic restart after update.
