### ISSUE TITLE
"Spring crashed"

### ISSUE THREAD

**Issue by abma** [Yaribz/SPADS#29]
since the[ lobby server update ](https://springrts.com/phpbb/viewtopic.php?f=38&t=36398&p=583457)spads reports "Spring crashed" when starting a game:

[06:41:39] * [BA]Peewee * Launching game...
[06:41:45] * [BA]Peewee * Spring crashed ! (running time: 6 seconds)

an idea why this happens?

the dev server which uses the updated version is running at lobby.springrts.com:7000

**Comment by abma** [comment]
(temporary reverted to the old version, but...hu?)

**Comment by abma** [comment]
not sure if related:

old server:
2017-09-15T06:38:46 Detecting local IP:
2017-09-15T06:38:46 127.0.1.1
2017-09-15T06:38:46 Detecting online IP:
2017-09-15T06:38:51 not online

new server:
2017-09-15 04:57:21 INFO  DataHandler.detectIp:400  Detecting local IP:
2017-09-15 04:57:21 INFO  DataHandler.detectIp:402  78.46.100.157
2017-09-15 04:57:21 INFO  DataHandler.detectIp:404  Detecting online IP:
2017-09-15 04:57:21 INFO  DataHandler.detectIp:412  78.46.100.157

**Comment by Yaribz** [comment]
> an idea why this happens?

Yes, uberserver sent inconsistent data to SPADS which just wrote them in the startscript to launch the game.

SPADS is quite protected against lobby server inconsistencies, but spring-dedicated isn't.

**Comment by abma** [comment]
can you be more specific? what was inconsistent?

**Comment by Yaribz** [comment]
I don't know exactly, I just noticed inconsistencies could be transmitted from lobby server to spring-dedicated by SPADS. I will update SPADS so that it also protects spring-dedicated from lobby server inconsistencies, but if you want more details you need to ask autohost owners who had autohosts running during your test to check their logs.

**Comment by abma** [comment]
script.txt generated by spads:
http://paste.springfiles.com/view/raw/c5fb12ca

[PLAYER0]
  {
    Name=[AG]abma;
    Password=5903a10c;
    Spectator=0;
    Team=0;
    CountryCode=DE;
    Rank=6;
    AccountId=30072;
    Skill=(35);
  }
  [PLAYER1]
  {
    Name=[AG]abma;
    Password=5903a10c;
    Spectator=0;
    Team=0;
    CountryCode=DE;
    Rank=6;
    AccountId=30072;
    Skill=(35);
  }


infolog.txt:
http://paste.springfiles.com/view/raw/63d38d6a

"Fatal: Spring: Incorrect/Missing content: 
GameSetup: Player 1 has name [AG]abma which is already taken"

**Comment by abma** [comment]
raw log of lobby commands between spads and lobby-server:

http://paste.springfiles.com/view/raw/3f4a90cf

clearly a lobby server bug:
"JOINEDBATTLE 54 [AG]abma.JOINEDBATTLE 54 [AG]abma 5903a10c"

but this shouldn't make users appear twice in script .txt :)
