### ISSUE TITLE
options can be set beyond game/engine limits

### ISSUE THREAD

**Issue by abma** [Yaribz/SPADS#30]
number 10000.000000 option limitscore exceeds boundaries 500.000000 5000.000000

**Comment by Yaribz** [comment]
AFAIK, options values _are_ checked...

which game ? which autohost ?
relevant lines of battlePresets.conf ?
did you type any SPADS command to change the option value ?

**Comment by abma** [comment]
> which game?
Balanced Annihilation V9.47
> which autohost ?
OverKillHost1
>  relevant lines of battlePresets.conf ?
idk, thats what is received via lobby SETSCRIPTTAGS:
game/modoptions/limitscore=10000

> relevant lines of battlePresets.conf ?
idk

>  did you type any SPADS command to change the option value ?

no, i just joined the autohost

**Comment by Yaribz** [comment]
According to the "!list bSettings" result, the autohost owner chose to overwrite this modoption definition in his battlePresets.conf file. SPADS makes it possible to redefine modoptions ranges if you really want it, but by default it complies with the boundaries provided by the mod.

**Comment by abma** [comment]
ok, pm'ed Shockwave who should be the autohost owner: he can hopefully provide more feedback.
