### ISSUE TITLE
Restrict !promote command when game is full

### ISSUE THREAD

**Issue by FabriceFABS** [Yaribz/SPADS#33]
When numbers of players are reached from nbTeams / Teamsize exactly.
With this, it avoids %p (nil) value taking a blank space in the message, like on BlackHoleHost2 for instance below :
```
[16:53:55] * BlackHoleHost2 * player(s) needed for battle "The BlackHoleHost - Revenge" [Balanced Annihilation V9.43, DeltaSiegeDry] ([AFUS]Ares)
[16:54:32] * [FAST]AutoHost1 * 60 player(s) needed for battle "** Tech Annihilation **" [Tech Annihilation v2.41.0, techno lands 3v3 v2] ([DIE]Vatermoerder)
```
You can, for instance, reject !promote command with a message like :
Promote command is not needed, game is already full.

Reported ("talked" exactly) here > https://springrts.com/phpbb/viewtopic.php?f=92&t=36420&p=583721#p583721

**Comment by Yaribz** [comment]
Afaik, the promote message configured on BlackHole hosts was modified to not print the number of "wanted" players computed by SPADS (nbTeams * teamSize - actualNumberOfPlayers).
This has nothing to do with !promote being used while battle is full.

**Comment by FabriceFABS** [comment]
Sorry, no, I remember I noticed this, some years ago.

Sorry to re-open it, I did the test just now on [ACE]Metallic 1v1 autohost, 104, with Phoenix Annihilation 1.01.

I changed my state from spec to play, I need a player.
```
[10:48:16]	<[ACE]FabriceFABS>	!promote
[10:48:16]	<*>	[ACE]Metallic * Promoting battle in #main, #fr, #[ACE]


[10:48:16]	<*>	[ACE]Metallic * We need for | Phoenix Annihilation V1.01 | 1 players | on Tundra map | JOIN NOW to make SPRING Great Again *\o/* !
```
-
- << It annoys me the GIT grabs CR.
-
I add a bot, and game is ready to play.
However, I want to spam a little bit... Let's promote for nothing :
```
10:49:44]	<[ACE]FabriceFABS>	!promote
[10:49:44]	<*>	[ACE]Metallic * Promoting battle in #main, #fr, #[ACE]


[10:49:44]	<*>	[ACE]Metallic * We need for | Phoenix Annihilation V1.01 | players | on Tundra map | JOIN NOW to make SPRING Great Again *\o/* !
```
PS : And my promote msg got the %p as you noticed above.
So can you add eventually a little fix that, makes impossible to !promote when wanted players = 0 with an error message ?

Thank you

**Comment by Yaribz** [comment]
using !promote when a bot is in the battle = I want a human player to join to replace the bot

This is a perfectly correct use of !promote in my point of view...

**Comment by Yaribz** [comment]
Concerning the %p being empty when target number of players/bots is reached is normal, yes.
What I was saying is just that %p had been removed on some hosts some time ago, because the autohost admins didn't want to print the number of missing players from SPADS point of view, they just wanted to promote the fact that "some players" are needed, not a specific number.

**Comment by FabriceFABS** [comment]
Sorry OK, I didn't understand it in that way.

**Comment by FabriceFABS** [comment]
> 0.12.2a: prevent using !promote command when battle is locked or full

I don't understand finally : Seems you did an update to prevent it in a such case ?

**Comment by Yaribz** [comment]
!promote should not be used when battle is _full of human players,_. But if battle is full because of AI bots, it makes sense to use !promote if you want to replace AI bots by human players.

**Comment by FabriceFABS** [comment]
I agree totally for your last message just above mine's.
> using !promote when a bot is in the battle = I want a human player to join to replace the bot
> 
> This is a perfectly correct use of !promote in my point of view...

I made this way totally by hazard, because I didn't got any player to make the test for showing the fact that %p disappear :)

And finally an update came... Good :+1:
