### ISSUE TITLE
Code to fix : Undefined value as ARRAY

### ISSUE THREAD

**Issue by FabriceFABS** [Yaribz/SPADS#35]
**In console, I discover that Spads gave me back the prompt :**
> NOTICE   - [SPADS] Spring archives have been modified 1 minute and 26 seconds ago, auto-reloading archives...
> Can't use an undefined value as an ARRAY reference at ./spads.pl line 1234.
> 

-
**Last line in spads.log :**
> 20170930160204 - NOTICE   - [SPADS] Spring archives have been modified 1 minute and 26 seconds ago, auto-reloading archives...
-

And the line on spads.pl 0.12.2 (or 0.12.2a) is
`return 0 unless @{$r_availableMods};`

**Comment by Yaribz** [comment]
I think it is the same bug as before: for some reason the unitsync library crashes...
Did you take a look at the unitsync.log file before restarting the SPADS instance ?

**Comment by FabriceFABS** [comment]
Sorry I totally forgot it.

**Comment by Yaribz** [comment]
I reopen this because I will try to make SPADS resilient to unitsync crashes...

**Comment by Yaribz** [comment]
I tried to improve unitsync library crash handling in SPADS 0.12.3, please reopen if it happens again
