### ISSUE TITLE
Stuck on loading unitsync library / interface module

### ISSUE THREAD

**Issue by springjools** [Yaribz/SPADS#37]
Gets stuck doing this:

jools@spring1:~/berries$ perl spads.pl etc/semprini.conf
NOTICE   - [SPADS] Initializing SPADS 0.12.2a
NOTICE   - [SPADS] Loading Spring archives using unitsync library version 98 ..

Also when reinstalling it gets stuck on loading this:

ble,testing,unstable,...) [104.0] ? 103.0
NOTICE   - [SpadsInstaller] Spring 103.0 is already installed
NOTICE   - [SpadsInstaller] SPADS components are up to date, proceeding with installation...
NOTICE   - [SpadsInstaller] Perl Unitsync interface module already exists, skipping generation (use "-g" flag to force generation)
7/15 - Please enter the absolute path of the Spring data directory containing the games and maps hosted by the autohost, or enter "new" to use a new directory instead [/home/jools/.spring] ? /ho^[OD^[OD^[OD^H^H^H^H^H^H
7/15 - Please enter the absolute path of the Spring data directory containing the games and maps hosted by the autohost, or enter "new" to use a new directory instead [/home/jools/.spring] ? /home/jools/data
NOTICE   - [SpadsInstaller] Checking Perl Unitsync interface module...

I have 4 autohosts using the same etc and var conf, but different instances.

**Comment by Yaribz** [comment]
Seemed to be only a problem with unitsync library and the number of mods/games in Spring data directory.
