### ISSUE TITLE
InGameMute plugin should still allow players to vote

### ISSUE THREAD

**Issue by Jazcash** [Yaribz/SPADS#60]
Currently, I believe it's this plugin that's preventing muted players from being able to vote, yet they are still included as part of the vote participation pool.

My suggestion would be to trim the optional message arg from any commands that have them and forward the bare command for muted players. e.g.

`!stop haha u suck` -> `!stop`

**Comment by Yaribz** [comment]
> Currently, I believe it's this plugin that's preventing muted players from being able to vote, yet they are still included as part of the vote participation pool.

It's not the plugin directly, it's the engine mute system which simply prevents the player's ingame messages from being sent to the autohost, as part of the mute functionality. So nothing can be done at SPADS side regarding this without engine changes... Maybe the plugin should remove muted players from SPADS vote pool, but currently they are still able to vote using lobby messages so I'm not sure...

**Comment by Jazcash** [comment]
I think this is a limitation of using `say` to transmit player commands, rather using a dedicated API through which clients can send/receive commands. Will close anyways if it's an engine issue
