### ISSUE TITLE
pluginsUpdateSkill correctly recieves the sigma value, but does not set the correct script tag of skillUncertainty

### ISSUE THREAD

**Issue by Beherith** [Yaribz/SPADS#62]
When a player joins a battle, the ratingmanager plugin's updatePlayerSkill correctly receives the players skill uncertainty value as the third element of the returned array. 

https://github.com/beyond-all-reason/spads_config_bar/blob/9aaefc0740154f314051d224e1f5d3200cc47a27/var/plugins/ratingmanager.py#L34

I also checked in spads.pl, and there its also correctly recieve 8.33

https://github.com/Yaribz/SPADS/blob/1f7fcf7bdf0f508236897e6da1c5d3fb992e5ff0/src/spads.pl#L15043

**Expected Behaviour**

"game/players/[teh]beherith/skilluncertainty" => "8.33",

**Observed behavior**

"game/players/[teh]beherith/skilluncertainty" => "3",

So the skill uncertainty is not passed to the correct script tag.

**Comment by Beherith** [comment]
Aha, seems like sigma gets floor(min(sigma,3)) here:

https://github.com/Yaribz/SPADS/blob/1f7fcf7bdf0f508236897e6da1c5d3fb992e5ff0/src/spads.pl#L6325

We are using floating point sigma, and openSkill's implementaions has a starting sigma of 8.33, which doesnt grow, only reduces. 

How shall we handle this case?

**Comment by Yaribz** [comment]
As explained [here](https://discord.com/channels/549281623154229250/564591092360675328/1111589203726303302), I'm actually currently waiting for a confirmation that your infra is ready to disable this mapping of the uncertainty value returned by plugins in SPADS.

**Comment by Yaribz** [comment]
3729f10
