### ISSUE TITLE
[Feature] Set/change privatehost password

### ISSUE THREAD

**Issue by FIr3baL** [Yaribz/SPADS#65]
Some users just asked, and i heard this more than 1 time before, if it is possible to change the password of a privatehost.

Since changing the password is limited by spring protocol, how about adding a parameter to `!privatehost` letting the user decide about that password.

This way groups/friends could always start their host with the same password and don't need to struggle with dictating those 4 letters anymore.

I would say it's a "nice to have" :)

**Comment by FIr3baL** [comment]
Closed for now, because there seems to a simpler solution serverside, which just allows friends to bypass password input.
https://discord.com/channels/549281623154229250/1266746654342778883

**Comment by Yaribz** [comment]
This was very easy to do, so I implemented it in 8b16bba. Files [ClusterManager.pm](https://github.com/Yaribz/SPADS/blob/master/plugins/officials/ClusterManager/ClusterManager.pm) and [ClusterManagerHelp.dat](https://github.com/Yaribz/SPADS/blob/master/plugins/officials/ClusterManager/ClusterManagerHelp.dat) just need to be updated on hosts if you want to be able to use custom passwords.

But the `!privateHost` command was already accepting a parameter which is the name of the cluster in which the private instance must be created (if not using default cluster). So the new password parameter must be given as second parameter (`*` can be provided as first parameter to use default cluster without having to give a specific cluster name).

**Comment by FIr3baL** [comment]
Thank you, that was quick :)
