### ISSUE TITLE
Extend RING telling clients the originator

### ISSUE THREAD

**Issue by FIr3baL** [Yaribz/SPADS#66]
I keep this issue short, because the topic was already described in deepth in other issues/PRs/chats.
https://github.com/beyond-all-reason/teiserver/issues/341
https://github.com/beyond-all-reason/teiserver/pull/397

The change was merged into teiserver and is running on integration server for about a week already :)
So `PROTOCOL_EXTENSIONS` is sent and the extended `RING` command is parsed correctly.

I'm quoting here the initial idea of @Yaribz from a private chat (hope that's fine)
> If you make Teiserver send `SERVERMSG @PROTOCOL_EXTENSIONS@ {"ring:originator":1}"` to SPADS clients after a successful `LOGIN` (just after the `ACCEPTED` command), then SPADS will be aware that the lobby server supports the two-parameters version of the `RING` command and it will be possible to implement it in SPADS core.

After all, the `RING` command from spads would look like this:
`RING <spadsUserName> <originator>`

This feature is "nice to have" and has absolutly no prio.

**Comment by Yaribz** [comment]
support added in SPADS 0.13.31
